### ISSUE TITLE
Ignores compilerOptions.outDir property on tsconfig.json

### ISSUE THREAD

**Issue by rahuldahal** [gilamran/tsc-watch#131]
**Context**
I've included the `outDir` property in the `tsconfig.json` file.
![image](https://user-images.githubusercontent.com/93955718/146641446-6a8d6dc6-c842-43b5-a4aa-b9ce701a6452.png)

**Problem**
But, when I run `tsc-watch ./typescriptDir/file.ts`, it compiles it in the same directory. Like, `./typescriptDir/file.js`

**Expected Behavior**
 The `tsc-watch ./typescriptDir/file.ts` command should output the compiled code in the directory mentioned in `outDir`.
 Like, `./build/file.js`

**Comment by MoSheikh** [comment]
I'm currently getting the same issue.

**Comment by gilamran** [comment]
This is a regular `tsc` (Typescript) behavior.
Try doing the same with `tsc` instead of `tsc-watch` and you will get the same result.

You have two options when running the compile (You can't mix the two):
1. Give it options and files to compile
2. Give it a project file (tsconfig.json) with all your options and files.

**Comment by gilamran** [comment]
still relevant?

**Comment by rahuldahal** [comment]
> still relevant?

Nope!
Is fixed by following your suggestion
