### ISSUE TITLE
Does not work with TypeScript 2.9.2.

### ISSUE THREAD

**Issue by sjohnsonaz** [gilamran/tsc-watch#29]
When using TypeScript 2.9.2, the onSuccess callback is never called.

**Comment by btxtiger** [comment]
Works for me with 2.9.2

**Comment by asztal** [comment]
It's been causing us issues. Instead of having typescript as a peer dependency, it installs it as a dependency of its own (using "*", as well). Perhaps this only affects yarn users.

In our case that actually resulted in us having two versions of typescript installed in our package - the one specified in our package.json (2.9.2), and the one tsc-watch had already installed previously (2.8.3). Installing 2.9.2 doesn't upgrade tsc-watch's version, because as far as yarn is concerned, 2.8.3 still matches `*`. (Yarn is possibly being stupid here, 2.9.2 _also_ matches `*`...)

In any case, perhaps it would be better for it to have typescript as a peerDependency instead so that it can simply inherit the correct version of typescript? If someone were deliberately using an older version of typescript, to avoid build errors (since new versions of typescript often introduce new errors for existing code), this could cause them problems if they got a new version of typescript without expecting it.

In my case, I have added a [resolution](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to my package.json.
