### ISSUE TITLE
Files with '.js' extensions are ignored even if set "allowJs": true

### ISSUE THREAD

**Issue by kkorus** [gilamran/tsc-watch#75]
My script:
`    "start:dev": "tsc-watch src/index.ts --outDir ./dist --onSuccess 'ts-node -r tsconfig-paths/register src/index.ts'",`

Making changes in TypeScript file triggers restart but in '.js' files not.

**Comment by gilamran** [comment]
Why would you use `tsc-watch` along with `ts-node`?
If you compile your code into the `dist` folder, use `node` to run the output... not `ts-node`
I guess that this is the reason `.js` files are being ignored.

If `.js` file are still being ignored, please provide a more detailed example to reproduce the issue.
Thanks for the Issue!

**Comment by kkorus** [comment]
Well I need  `ts-node` because of `-r tsconfig-paths/register`

**Comment by gilamran** [comment]
Sorry, I'm not familiar with `-r` can you explain?

**Comment by gilamran** [comment]
After reading some more about the `programmatic` section of `ts-node` I think that I understand why was created... `ts-node` lets you transpile "on-the-fly" instead of transpiling ALL your code... This is a good idea if you want `ts-node` to run as fast as possible when you start it.

But in `tsc-watch` you don't need `ts-node` at all... Yes you compile ALL the code in the first time, but any future compilation (Because of the `watch`) will be very fast!

**Comment by quicksilverr** [comment]
Hey @gilamran could you please share how can we use tsconfig-paths with tsc-watch?

**Comment by quicksilverr** [comment]
Alright, found the solution for it.

Here are the steps I performed - 

- First, follow theses [steps](https://github.com/nonara/ts-patch#setup), and setup [ts-patch](https://github.com/nonara/ts-patch)
- Then, install [typescript-transform-paths](https://github.com/LeDDGroup/typescript-transform-paths) as a dev-dependency.
- Check this [example](https://github.com/LeDDGroup/typescript-transform-paths#example-config). Add, it as a plugin in your tsconfig.json.
